### ISSUE TITLE
Bug in container handling for ThreadAwareModules

### ISSUE THREAD

**Issue by ramo-j** [log2timeline/dftimewolf#503]
Currently, if a module wants to pop input containers, and store the same type of containers after processing, there is a bug that means no containers would be stored.

The relevant functionality is implemented as follows at the moment:

```
        with ThreadPoolExecutor(max_workers=module.GetThreadPoolSize())  executor:
          for container in GetContainers(module.GetThreadOnContainerType()):
            futures.append(submit(module.Process, container))
<snip>
        if not module.KeepThreadedContainersInState():
          self.GetContainers(module.GetThreadOnContainerType(), True)
```

If the module wants to pop it's input containers, they are removed after `Process`. However, if a module (for example, `SCPExporter`) uses the same container type as input and output, then they are added in Process, then removed afterwards.

**Comment by tomchop** [comment]
This reminds me of a discussion that we had about "targeted containers". It sounds like we would avoid some of these problems (and have no further need for `pop`ing containers) by being able to tell a module which containers from which module it should be processing (e.g. only process File containers from SCPExporter). This would probably have to be defined at the recipe level.

Otherwise, as stop-gap here would be to get all containers and store them in a list, popping them before the Process() methods are called. Something like

```python
        with ThreadPoolExecutor(max_workers=module.GetThreadPoolSize())  executor:
          pop = not module.KeepThreadedContainersInState():
          containers = self.GetContainers(module.GetThreadOnContainerType(), pop)
          for container in containers:
            futures.append(submit(module.Process, container))
<snip>
```
